#stateful set config for mongo
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: production
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command: ["/bin/sh","-c"]
          args: ["echo 2J2W5Jm7G38y169r8s5T1dW0uxG4t0YN > mongo.key; chmod 600 mongo.key; mongod --replSet epesi --keyFile mongo.key --smallfiles --noprealloc --bind_ip_all"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: persistent-storage
      #annotations:
        #volume.beta.kubernetes.io/storage-class: "fastdisk"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
